import { register } from '../service';
import { logout } from '../store/reducers/userSlice';

export const message = {
  loginSuccess: 'Login successful!',
  loginFailed: 'Login failed. Please try again.',
  networkError: 'Network error. Please check your internet connection.',
  login_to_view: 'login_to_view',
  requestLogin: 'requestLogin',
  text1Error: 'text1Error',
  text1Success: 'text1Success',
  min_max: 'min_max',
  enter_userName: 'enter_userName',
  enter_password: 'enter_password',
  register: 'register',
  other_register: 'other_register',
  other_login: 'other_login',
  have_account: 'have_account',
  nothave_account: 'nothave_account',
  agree: 'agree',
  otp_error: 'otp_error',
};

export const text = {
  login: 'login',
  welcome: 'welcome',
  home: 'home',
  profile: 'profile',
  settings: 'settings',
  back: 'back',
  remember: 'remember_me',
  forgot: 'forgot_pw',
  logout: 'logout',
  menu: 'Menu',
  register: 'register',
  transaction: 'Transaction',
  report: 'Report',
  user: 'User',
  company_name: 'company_name',
  search: 'search',
  find: 'find',
  find_project: 'find_project',
  find_district: 'find_district',
  find_ward: 'find_ward',
  find_street: 'find_street',
  find_location: 'find_location',
  property_type: 'property_type',
  property_info: 'property_info',
  price_range: 'price_range',
  acreage: 'acreage',
  bedrooms: 'bedrooms',
  bathrooms: 'bathrooms',
  floors: 'floors',
  language: 'language',
  no_data: 'no_data',
  property: 'property',
  arrange: 'arrange',
  guide: 'guide',
  faq: 'faq',
  regulations: 'regulations',
  report_issue: 'report_issue',
  about_us: 'about_us',
  of_us: 'of_us',
  terms_and_conditions: 'terms_and_conditions',
  privacy_policy: 'privacy_policy',
  account_management: 'account_management',
  notification_settings: 'notification_settings',
  delete_account_request: 'delete_account_request',
  login_to_view: 'login_to_view',
  business_registration: 'business_registration',
  responsible_person: 'responsible_person',
  company_address: 'company_address',
  version: 'version',
  description: 'description',
  property_features: 'property_features',
  created: 'created',
  create_post: 'create_post',
  upload_image: 'upload_image',
  exit: 'exit',
  step: 'step',
  demand: 'demand',
  sale: 'sale',
  rent: 'rent',
  more_info: 'more_info',
  prop_location: 'prop_location',
  enter_location: 'enter_location',
  enter_area: 'enter_area',
  enter_price: 'enter_price',
  enter_sort: 'enter_sort',
  enter_unit: 'enter_unit',
  enter_otp: 'enter_otp',
  pick_location: 'pick_location',
  main_info: 'main_info',
  price: 'price',
  unit: 'unit',
  price_m2: 'price/m²',
  deal: 'deal',
  bilion: 'bilion',
  milion: 'milion',
  thousand: 'thousand ',
  coin: 'coin',
  other_info: 'other_info',
  legal: 'legal',
  furnishing: 'Furnishing',
  frontage: 'frontage',
  accessRoad: 'accessRoad',
  contact_info: 'contact_info',
  fullname: 'fullname',
  email: 'email',
  phone: 'phone',
  title: 'title',
  optional: 'optional',
  nothave: 'nothave',
  have: 'have',
  redbook: 'redbook',
  waiting: 'waiting',
  full: 'full',
  highClass: 'highClass',
  availableFrom: 'availableFrom',
  electricityPrice: 'electricityPrice',
  waterPrice: 'waterPrice',
  internetPrice: 'internetPrice',
  now: 'now',
  week: 'week',
  month: 'month',
  supplier: 'supplier',
  owner: 'owner',
  title_des: 'title_des',
  image: 'image',
  selected: 'selected',
  saved_post: 'saved_post',
  area_asc: 'area_asc',
  area_desc: 'area_desc',
  price_asc: 'price_asc',
  price_des: 'price_des',
  created_desc: 'created_desc',
  sort: 'sort',
  under: 'under',
  min: 'min',
  max: 'max',
  reset: 'reset',
  submit: 'submit',
  cancel: 'cancel',
  from: 'from',
  to: 'to',
  today: 'today',
  expand: 'expand',
  collapse: 'collapse',
  //modal
  modal: {
    chooseHouseType: 'modal.chooseHouseType',
    chooseDirection: 'modal.chooseDirection',
    houseDirection: 'modal.houseDirection',
    balconyDirection: 'modal.balconyDirection',

    chooseUnit: 'modal.chooseUnit',
    houseType: {
      apartment: 'modal.houseType.apartment',
      mini_apartment: 'modal.houseType.mini_apartment',
      house: 'modal.houseType.house',
      villa: 'modal.houseType.villa',
      roadhouse: 'modal.houseType.roadhouse',
      shophouse: 'modal.houseType.shophouse',
      projectLand: 'modal.houseType.projectLand',
      land: 'modal.houseType.land',
      farm: 'modal.houseType.farm',
      condotel: 'modal.houseType.condotel',
      warehouse: 'modal.houseType.warehouse',
      other: 'modal.houseType.other',
    },
    direction: {
      east: 'modal.direction.Đông',
      west: 'modal.direction.Tây',
      south: 'modal.direction.Nam',
      north: 'modal.direction.Bắc',
      northeast: 'modal.direction.Đông Bắc',
      southeast: 'modal.direction.Đông Nam',
      northwest: 'modal.direction.Tây Bắc',
      southwest: 'modal.direction.Tây Nam',
    },
  },
};
export const ICONS = {
  search: require('../assets/icons/search.png'),
  search_focus: require('../assets/icons/search_focus.png'),
  heart: require('../assets/icons/heart.png'),
  heart_focus: require('../assets/icons/heart_focus.png'),
  heart_like: require('../assets/icons/heart_like.png'),
  user: require('../assets/icons/user.png'),
  user_focus: require('../assets/icons/user_focus.png'),
  show: require('../assets/icons/show_pass.png'),
  hide: require('../assets/icons/hide.png'),
  clear: require('../assets/icons/clear.png'),
  checked: require('../assets/icons/checked.png'),
  unchecked: require('../assets/icons/unchecked.png'),
  username: require('../assets/icons/username.png'),
  password: require('../assets/icons/password.png'),
  google: require('../assets/icons/google.png'),
  apple: require('../assets/icons/apple.png'),
  valid: require('../assets/icons/valid.png'),
  dot: require('../assets/icons/dot.png'),
  back: require('../assets/icons/back.png'),
  down: require('../assets/icons/down.png'),
  up: require('../assets/icons/up.png'),
  sort_down: require('../assets/icons/sort_down.png'),
  bath: require('../assets/icons/bath.png'),
  bed: require('../assets/icons/bed.png'),
  location: require('../assets/icons/location.png'),
  phone: require('../assets/icons/phone.png'),
  noti: require('../assets/icons/noti.png'),
  question: require('../assets/icons/question.png'),
  issue: require('../assets/icons/issue.png'),
  about: require('../assets/icons/about.png'),
  clause: require('../assets/icons/clause.png'),
  clause_focus: require('../assets/icons/clause_focus.png'),
  privacy: require('../assets/icons/privacy.png'),
  remove_user: require('../assets/icons/remove_user.png'),
  logout: require('../assets/icons/logout.png'),
  radio_checked: require('../assets/icons/radio_checked.png'),
  radio_unchecked: require('../assets/icons/radio_unchecked.png'),
  apartment: require('../assets/icons/apartment.png'),
  mini_apartment: require('../assets/icons/mini_apartment.png'),
  land: require('../assets/icons/land.png'),
  all_house: require('../assets/icons/all_house.png'),
  other: require('../assets/icons/other.png'),
  house: require('../assets/icons/house.png'),
  warehouse: require('../assets/icons/warehouse.png'),
  villa: require('../assets/icons/villa.png'),
  roadhouse: require('../assets/icons/roadhouse.png'),
  shophouse: require('../assets/icons/shophouse.png'),
  projectLand: require('../assets/icons/projectLand.png'),
  farm: require('../assets/icons/farm.png'),
  condotel: require('../assets/icons/condotel.png'),
  share: require('../assets/icons/share.png'),
  price: require('../assets/icons/price.png'),
  expand: require('../assets/icons/expand.png'),
  direction: require('../assets/icons/direction.png'),
  furniture: require('../assets/icons/furniture.png'),
  plus: require('../assets/icons/plus.png'),
  plus_focus: require('../assets/icons/plus_focus.png'),
  tag: require('../assets/icons/tag.png'),
  tag_focus: require('../assets/icons/tag_focus.png'),
  key: require('../assets/icons/key.png'),
  key_focus: require('../assets/icons/key_focus.png'),
  edit: require('../assets/icons/edit.png'),
  minus: require('../assets/icons/minus.png'),
  image: require('../assets/icons/image.png'),
  language: require('../assets/icons/language.png'),
};

export const IMAGES = {
  logo: require('../assets/images/company-logo.png'),
  avartar: require('../assets/images/avt_male.jpg'),
  bocongthuong: require('../assets/images/bocongthuong.png'),
};

export const link = {
  url: 'https://bds.foxai.com.vn:8441',
  company: 'https://fox.ai.vn/',
};
