import { logout } from '../store/reducers/userSlice';

export const MESSAGES = {
  loginSuccess: 'Login successful!',
  loginFailed: 'Login failed. Please try again.',
  networkError: 'Network error. Please check your internet connection.',
};

export const text = {
  login: 'login',
  home: 'home',
  profile: 'profile',
  settings: 'settings',
  accept: 'Xác nhận',
  cancel: 'Hủy bỏ',
  logout: 'logout',
  menu: 'Menu',
  register: 'Đăng kí tài khoản',
  transaction: 'Transaction',
  report: 'Report',
  user: 'User',
  welcome: 'Chào mừng quay trở lại',
  company_name: 'company_name',
  search: 'search',
  find_project: 'find_project',
  find_district: 'find_district',
  find_ward: 'find_ward',
  find_street: 'find_street',
  property_type: 'property_type',
  price_range: 'price_range',
  acreage: 'acreage',
  bedrooms: 'bedrooms',
  language: 'language',
  no_data: 'no_data',
  property: 'property',
  arrange: 'arrange',
  guide: 'guide',
  faq: 'faq',
  report_issue: 'report_issue',
  about_us: 'about_us',
  terms_and_conditions: 'terms_and_conditions',
  privacy_policy: 'privacy_policy',
  account_management: 'account_management',
  notification_settings: 'notification_settings',
  delete_account_request: 'delete_account_request',
  login_to_view: 'login_to_view',
  business_registration: 'business_registration',
  responsible_person: 'responsible_person',
  company_address: 'company_address',
  version: 'version',

  //modal
  modal: {
    chooseHouseType: 'modal.chooseHouseType',
    chooseDirection: 'modal.chooseDirection',
    houseType: {
      apartment: 'modal.houseType.apartment',
      mini_apartment: 'modal.houseType.mini_apartment',
      house: 'modal.houseType.house',
      villa: 'modal.houseType.villa',
      roadhouse: 'modal.houseType.roadhouse',
      shophouse: 'modal.houseType.shophouse',
      projectLand: 'modal.houseType.projectLand',
      land: 'modal.houseType.land',
      farm: 'modal.houseType.farm',
      condotel: 'modal.houseType.condotel',
      warehouse: 'modal.houseType.warehouse',
      other: 'modal.houseType.other',
    },
    direction: {
      east: 'modal.direction.Đông',
      west: 'modal.direction.Tây',
      south: 'modal.direction.Nam',
      north: 'modal.direction.Bắc',
      northeast: 'modal.direction.Đông Bắc',
      southeast: 'modal.direction.Đông Nam',
      northwest: 'modal.direction.Tây Bắc',
      southwest: 'modal.direction.Tây Nam',
    },
  },
};
export const ICONS = {
  search: require('../assets/icons/search.png'),
  search_focus: require('../assets/icons/search_focus.png'),
  heart: require('../assets/icons/heart.png'),
  heart_focus: require('../assets/icons/heart_focus.png'),
  user: require('../assets/icons/user.png'),
  user_focus: require('../assets/icons/user_focus.png'),
  show: require('../assets/icons/show_pass.png'),
  hide: require('../assets/icons/hide.png'),
  clear: require('../assets/icons/clear.png'),
  checked: require('../assets/icons/checked.png'),
  unchecked: require('../assets/icons/unchecked.png'),
  username: require('../assets/icons/username.png'),
  password: require('../assets/icons/password.png'),
  google: require('../assets/icons/google.png'),
  apple: require('../assets/icons/apple.png'),
  valid: require('../assets/icons/valid.png'),
  dot: require('../assets/icons/dot.png'),
  back: require('../assets/icons/back.png'),
  down: require('../assets/icons/down.png'),
  sort_down: require('../assets/icons/sort_down.png'),
  bath: require('../assets/icons/bath.png'),
  bed: require('../assets/icons/bed.png'),
  location: require('../assets/icons/location.png'),
  phone: require('../assets/icons/phone.png'),
  noti: require('../assets/icons/noti.png'),
  question: require('../assets/icons/question.png'),
  issue: require('../assets/icons/issue.png'),
  about: require('../assets/icons/about.png'),
  clause: require('../assets/icons/clause.png'),
  privacy: require('../assets/icons/privacy.png'),
  remove_user: require('../assets/icons/remove_user.png'),
  logout: require('../assets/icons/logout.png'),
  radio_checked: require('../assets/icons/radio_checked.png'),
  radio_unchecked: require('../assets/icons/radio_unchecked.png'),
  apartment: require('../assets/icons/apartment.png'),
  mini_apartment: require('../assets/icons/mini_apartment.png'),
  land: require('../assets/icons/land.png'),
  all_house: require('../assets/icons/all_house.png'),
  other: require('../assets/icons/other.png'),
  house: require('../assets/icons/house.png'),
  warehouse: require('../assets/icons/warehouse.png'),
  villa: require('../assets/icons/villa.png'),
  roadhouse: require('../assets/icons/roadhouse.png'),
  shophouse: require('../assets/icons/shophouse.png'),
  projectLand: require('../assets/icons/projectLand.png'),
  farm: require('../assets/icons/farm.png'),
  condotel: require('../assets/icons/condotel.png'),
};

export const IMAGES = {
  logo: require('../assets/images/company-logo.png'),
  avartar: require('../assets/images/avt_male.jpg'),
  bocongthuong: require('../assets/images/bocongthuong.png'),
};
